import type { ActivityDefinition, AppSettings } from './models'

const now = () => new Date().toISOString()

export function createDefaultActivities(): ActivityDefinition[] {
  const timestamp = now()

  return [
    {
      id: 'preset-water',
      name: '喝水',
      icon: 'water',
      tone: 'link',
      mode: 'instant',
      defaultAmount: '250',
      unit: 'ml',
      sortOrder: 0,
      isArchived: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'preset-toilet',
      name: '小手',
      icon: 'toilet',
      tone: 'neutral',
      mode: 'instant',
      defaultAmount: '1',
      unit: '次',
      sortOrder: 1,
      isArchived: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'preset-toilet-large',
      name: '大手',
      icon: 'toilet',
      tone: 'accent',
      mode: 'instant',
      defaultAmount: '1',
      unit: '次',
      sortOrder: 2,
      isArchived: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'preset-meal',
      name: '吃饭',
      icon: 'meal',
      tone: 'accent',
      mode: 'instant',
      defaultAmount: '1',
      unit: '次',
      sortOrder: 3,
      isArchived: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'preset-snack',
      name: '零食',
      icon: 'snack',
      tone: 'warning',
      mode: 'instant',
      defaultAmount: '50',
      unit: 'g',
      sortOrder: 4,
      isArchived: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'preset-fruit',
      name: '水果',
      icon: 'fruit',
      tone: 'success',
      mode: 'instant',
      defaultAmount: '100',
      unit: 'g',
      sortOrder: 5,
      isArchived: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'preset-soda',
      name: '屈臣氏苏打汽水饮料',
      icon: 'soda',
      tone: 'link',
      mode: 'instant',
      defaultAmount: '330',
      unit: 'ml',
      sortOrder: 6,
      isArchived: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'preset-coffee',
      name: '咖啡',
      icon: 'coffee',
      tone: 'warning',
      mode: 'instant',
      defaultAmount: '1',
      unit: '次',
      sortOrder: 7,
      isArchived: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'preset-exercise',
      name: '锻炼',
      icon: 'exercise',
      tone: 'danger',
      mode: 'timer',
      defaultAmount: '1',
      unit: '次',
      sortOrder: 8,
      isArchived: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      id: 'preset-drive',
      name: '开车',
      icon: 'drive',
      tone: 'warning',
      mode: 'timer',
      defaultAmount: '1',
      unit: '次',
      sortOrder: 9,
      isArchived: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ]
}

export function createDefaultSettings(): AppSettings {
  const timestamp = now()
  return {
    id: 'app',
    weekStartsOn: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
  }
}
